config/routes.rb
Rails.application.routes.draw do
  resources :attachments
  resources :nodes
  root 'nodes#index'
end

app/models/add_file_to_attachment.rb
class AddFileToAttachment < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :node, inverse_of: :attachments

  has_attached_file :file

  validates_attachment_content_type :file, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif", "text/html"]
end

app/models/node.rb
class Node < ApplicationRecord
  has_many :attachments, inverse_of: :node, dependent: :destroy

  accepts_nested_attributes_for :attachments, reject_if: proc { |a| a[:file].blank? }, allow_destroy: true

  validates :name, presence: true
end

app/controllers/add_file_to_attachments_controller.rb
class AddFileToAttachmentsController < ApplicationController
  before_action :set_add_file_to_attachment, only: [:show, :edit, :update, :destroy]

  # GET /add_file_to_attachments
  # GET /add_file_to_attachments.json
  def index
    @add_file_to_attachments = AddFileToAttachment.all
  end

  # GET /add_file_to_attachments/1
  # GET /add_file_to_attachments/1.json
  def show
  end

  # GET /add_file_to_attachments/new
  def new
    @add_file_to_attachment = AddFileToAttachment.new
  end

  # GET /add_file_to_attachments/1/edit
  def edit
  end

  # POST /add_file_to_attachments
  # POST /add_file_to_attachments.json
  def create
    @add_file_to_attachment = AddFileToAttachment.new(add_file_to_attachment_params)

    respond_to do |format|
      if @add_file_to_attachment.save
        format.html { redirect_to @add_file_to_attachment, notice: 'Add file to attachment was successfully created.' }
        format.json { render :show, status: :created, location: @add_file_to_attachment }
      else
        format.html { render :new }
        format.json { render json: @add_file_to_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /add_file_to_attachments/1
  # PATCH/PUT /add_file_to_attachments/1.json
  def update
    respond_to do |format|
      if @add_file_to_attachment.update(add_file_to_attachment_params)
        format.html { redirect_to @add_file_to_attachment, notice: 'Add file to attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @add_file_to_attachment }
      else
        format.html { render :edit }
        format.json { render json: @add_file_to_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /add_file_to_attachments/1
  # DELETE /add_file_to_attachments/1.json
  def destroy
    @add_file_to_attachment.destroy
    respond_to do |format|
      format.html { redirect_to add_file_to_attachments_url, notice: 'Add file to attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_add_file_to_attachment
      @add_file_to_attachment = AddFileToAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def add_file_to_attachment_params
      params.fetch(:add_file_to_attachment, {})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:file)
    end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]
  before_action :build_attachments, only: [:update, :edit]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
    2.times { @node.attachments.build }
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)
    2.times { @node.attachments.build }

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def build_attachments
    1.times { @node.attachments.build }
  end

  def set_node
    @node = Node.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def node_params
    params.require(:node).permit(:name, attachments_attributes: [:file])
  end
end

app/helpers/add_file_to_attachments_helper.rb
module AddFileToAttachmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/attachments/_form.html.erb
<%= form_for(attachment) do |f| %>
  <% if attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file %>
    <%= f.text_field :file %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attachments</h1>

<table>
  <thead>
    <tr>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.file %></td>
        <td><%= link_to 'Show', attachment %></td>
        <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
        <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File:</strong>
  <%= @attachment.file %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileUploads</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nodes/_file_fields.html.erb
<%= f.label :file %>
<%= f.file_field :file %>

app/views/nodes/_form.html.erb
<%= form_for(node, html: { multipart: true }) do |f| %>
  <% if node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
        <% node.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.fields_for :attachments do |f| %>
      <%= f.label :file %>
      <%= f.file_field :file %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing Node</h1>

<%= render 'form', node: @node %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nodes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td><%= node.name %></td>
        <td><%= link_to 'Show', node %></td>
        <td><%= link_to 'Edit', edit_node_path(node) %></td>
        <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New Node</h1>

<%= render 'form', node: @node %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @node.name %>
</p>

<p>

  <% @node.attachments.each do |attachment| %>
    <%= link_to attachment.file_file_name, attachment.file.url, target: '_blank' %>
  <% end %>
</p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>